### ISSUE TITLE
Skip oauth for testing with pubsub emulator

### ISSUE THREAD

**Issue by testower** [wingify/lua-resty-pubsub#2]
Is there a way to skip authentication so this can be tested with pubsub emulator?

Right now I am able to give the pubsub emulator ip adress and port, but get the following error:

 request.lua:64: batch_send(): Got error in handshake = closed

**Comment by Vasu7052** [comment]
Hi Tom, 
As of now, Authentication is a mandatory step in the library but we are working on supporting pubsub emulator as well. Hopefully you will be able to test the library with your local environment in next release.

Thank You

**Comment by testower** [comment]
Thanks, would you mind keeping this issue open and updating when you have it ready?

**Comment by Vasu7052** [comment]
Hi Tom,
We have added support for Pub/Sub emulator now. Do refer to the updated Readme.md for enabling emulator and other changes.
Closing this issue now.
Thanks
